locking/atomics: Explicitly include CONFIGs for atomic64_t type
Fixes the following error:

In file included from ../arch/arm64/kernel/vdso32/vgettimeofday.c:2:
In file included from ../arch/arm64/kernel/vdso32/datapage.h:1:
In file included from ../arch/arm64/kernel/vdso32/../vdso/datapage.h:20:
In file included from ../include/linux/bitops.h:18:
In file included from ../arch/arm64/include/asm/bitops.h:37:
In file included from ../include/asm-generic/bitops/atomic.h:5:
In file included from ../include/linux/atomic.h:5:
In file included from ../arch/arm64/include/asm/atomic.h:60:
../arch/arm64/include/asm/atomic_ll_sc.h:208:1: error: unknown type name 'atomic64_t'; did you mean 'atomic_t'?
ATOMIC64_OPS(sub, sub)
^
../arch/arm64/include/asm/atomic_ll_sc.h:201:2: note: expanded from macro 'ATOMIC64_OPS'
        ATOMIC64_OP_RETURN(_release,,  , l, "memory", __VA_ARGS__)      \
        ^
../arch/arm64/include/asm/atomic_ll_sc.h:154:53: note: expanded from macro 'ATOMIC64_OP_RETURN'
__LL_SC_PREFIX(atomic64_##op##_return##name(long i, atomic64_t *v))     \
                                                    ^
../include/linux/types.h:180:3: note: 'atomic_t' declared here
} atomic_t;
  ^

Signed-off-by: Danny Lin <danny@kdrag0n.dev>
Signed-off-by: Yousef Algadri <yusufgadrie@gmail.com>
Signed-off-by: Panchajanya1999 <panchajanya@azure-dev.live>
(cherry picked from commit 50f7ef853f66a605f1267a2131ace521085b2271)
Signed-off-by: Nauval Rizky <enuma.alrizky@gmail.com>